<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net8.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
		<RootNamespace>Tyuiu.AndrianovSA.Sprint2.Task5.V9.Lib</RootNamespace>
	</PropertyGroup>

	<ItemGroup>
		<Reference Include="tyuiu.cources.programming.interfaces">
			<HintPath>..\tyuiu.cources.programming.interfaces.dll</HintPath>
		</Reference>
	</ItemGroup>

</Project>